#!/bin/bash

set -x;
set -e;
rm -fr dist/;
encrust release;
# NB: trailing slash important for rsync
UPDATES_FOLDER="${HOME}/Storage/Sparkle/PINPal/Releases/";
mv -n dist/*.release.app.zip "${UPDATES_FOLDER}";

SPARKLE_VERSION="2.6.4";
SPARKLE_QUALNAME="Sparkle-${SPARKLE_VERSION}";
SPARKLE_VERSION_DIR="${HOME}/.local/firstparty/sparkle-project.org/${SPARKLE_QUALNAME}";

"${SPARKLE_VERSION_DIR}/bin/generate_appcast" \
    --account "im.glyph.and.this.is.my.sparkle.key" \
    "${UPDATES_FOLDER}";

rsync -avz --delete \
      "${UPDATES_FOLDER}" \
      public.glyph.im:/site/www.glyph.im/apps/pinpal/updates/;
