#!/bin/bash

# Download the Sparkle framework and place it into a known location for both
# development and CI purposes.

SPARKLE_VERSION="2.6.4";
SPARKLE_QUALNAME="Sparkle-${SPARKLE_VERSION}";
SPARKLE_ARCHIVE="${SPARKLE_QUALNAME}.tar.xz";
SPARKLE_VERSION_DIR="${HOME}/.local/firstparty/sparkle-project.org/${SPARKLE_QUALNAME}";

mkdir -p "${SPARKLE_VERSION_DIR}";
cd "${SPARKLE_VERSION_DIR}" || exit 1;
curl -LO "https://github.com/sparkle-project/Sparkle/releases/download/${SPARKLE_VERSION}/${SPARKLE_ARCHIVE}";
tar xf "${SPARKLE_ARCHIVE}";
