#!/bin/sh -x

pip-compile --strip-extras --quiet --upgrade --allow-unsafe --no-emit-index-url \
            --extra dev \
            -o dev-requirements.txt
pip-compile --strip-extras --quiet --upgrade --allow-unsafe --no-emit-index-url \
            --constraint ./dev-requirements.txt
pip-compile --strip-extras --quiet --upgrade --allow-unsafe --no-emit-index-url \
            --extra gui \
            -o "$(
            python3 -c '
import platform
print(platform.platform().split("-")[0])
'
)-gui.requirements.txt" \
            --constraint ./dev-requirements.txt\
            --constraint ./requirements.txt
