[build-system]
requires = [
  "setuptools>=42,<71.0.0",
  "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "pinpal"
authors = [{name = "Glyph", email = "glyph@glyph.im"}]
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
readme = "README.md"
dependencies = [
    "keyring",
    "horsephrase",
]

version = "2024.12.0"

[project.urls]
Home = "https://github.com/glyph/pinpal/"

[project.scripts]
pinpal = "pinpal:main"
